// PCLT Roster - source of truth
export const ROSTER = [
  "Doug Bedell",
  "Miranda Delatore",
  "Nicole Eckl",
  "Lauren Fields",
  "Chrissy Hand",
  "Greg Hart",
  "Jen Miesse",
  "John Priskorn",
  "Bridget Readey",
  "Bill Sicheneder",
  "Mike Waldman",
  "Megan Wetzel",
]

// Admins by name (must match ROSTER exactly)
export const ADMINS = ["Bridget Readey", "Greg Hart", "Megan Wetzel"]

// CMM brand avatar palette
export const PALETTE = ["#FF8F1C", "#E70865", "#01426A", "#008AD8"]

export function colorFor(name) {
  let h = 0
  for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) >>> 0
  return PALETTE[h % PALETTE.length]
}

export function initials(name) {
  const p = name.trim().split(/\s+/)
  return ((p[0]?.[0] || "") + (p[1]?.[0] || "")).toUpperCase() || name[0]?.toUpperCase() || "?"
}

// Returns "June 2026" style label for the previous completed month
export function previousMonthLabel() {
  const d = new Date()
  d.setDate(1)
  d.setMonth(d.getMonth() - 1)
  return d.toLocaleDateString("en-US", { month: "long", year: "numeric" })
}

// Returns "2026-06" style key for the previous completed month
export function previousMonthKey() {
  const d = new Date()
  d.setDate(1)
  d.setMonth(d.getMonth() - 1)
  const year = d.getFullYear()
  const month = String(d.getMonth() + 1).padStart(2, "0")
  return `${year}-${month}`
}

// Generate a cryptographically random token
export function generateToken() {
  const arr = new Uint8Array(12)
  crypto.getRandomValues(arr)
  return Array.from(arr, b => b.toString(36).padStart(2, "0")).join("").slice(0, 16)
}

// Token map: { token: voterName }
// Stored in votes.json under the key "_tokens"
// Shape of votes.json:
// {
//   "_tokens": { "abc123": "Greg Hart", ... },        // generated by admin
//   "2026-06": { "Greg Hart": "Miranda Delatore", ... } // month -> voter -> choice
// }
