// PCLT Roster - source of truth
export const ROSTER = [
  "Doug Bedell",
  "Miranda Delatore",
  "Nicole Eckl",
  "Lauren Fields",
  "Chrissy Hand",
  "Greg Hart",
  "Jen Miesse",
  "John Priskorn",
  "Bridget Readey",
  "Bill Sicheneder",
  "Mike Waldman",
  "Megan Wetzel",
]

// Admins by name (must match ROSTER exactly)
export const ADMINS = ["Bridget Readey", "Greg Hart", "Megan Wetzel"]

// CMM brand avatar palette
export const PALETTE = ["#FF8F1C", "#E70865", "#01426A", "#008AD8"]

// Shuffle the palette once per session so colors rotate on each load
const _sessionPalette = (() => {
  const p = [...PALETTE]
  for (let i = p.length - 1; i > 0; i--) {
    const j = Math.floor(Math.random() * (i + 1));
    [p[i], p[j]] = [p[j], p[i]]
  }
  return p
})()

export function colorFor(name) {
  const idx = ROSTER.indexOf(name)
  return idx === -1
    ? _sessionPalette[0]
    : _sessionPalette[idx % _sessionPalette.length]
}

export function initials(name) {
  const p = name.trim().split(/\s+/)
  return ((p[0]?.[0] || "") + (p[1]?.[0] || "")).toUpperCase() || name[0]?.toUpperCase() || "?"
}

// Returns "June 2026" style label for the previous completed month
export function previousMonthLabel() {
  const d = new Date()
  d.setDate(1)
  d.setMonth(d.getMonth() - 1)
  return d.toLocaleDateString("en-US", { month: "long", year: "numeric" })
}

// Returns "2026-06" style key for the previous completed month
export function previousMonthKey() {
  const d = new Date()
  d.setDate(1)
  d.setMonth(d.getMonth() - 1)
  const year = d.getFullYear()
  const month = String(d.getMonth() + 1).padStart(2, "0")
  return `${year}-${month}`
}

// ─── Auto-cutoff voting period ────────────────────────────────────────────────
// Voting closes at 5pm ET on the 5th of each month for the prior month.
// After cutoff, voting opens for the current month.
//
// Returns { monthKey, monthLabel, isClosed }
// isClosed: true only in the window between month-end and the 5th at 5pm ET

function isEDT(date) {
  // EDT: second Sunday in March through first Sunday in November
  const jan = new Date(date.getFullYear(), 0, 1).getTimezoneOffset()
  const jul = new Date(date.getFullYear(), 6, 1).getTimezoneOffset()
  return date.getTimezoneOffset() < Math.max(jan, jul)
}

export function getVotingPeriod() {
  const now = new Date()
  const etOffset = isEDT(now) ? -4 : -5
  const nowET = new Date(now.getTime() + etOffset * 60 * 60 * 1000)

  const day  = nowET.getUTCDate()
  const hour = nowET.getUTCHours() // 17 = 5pm

  const isPastCutoff = day > 5 || (day === 5 && hour >= 17)

  // Voting is always open — never a dead window. The month switches at the cutoff.
  const isClosed = false

  // Which month are we voting for?
  const target = new Date(nowET)
  target.setUTCDate(1)
  if (!isPastCutoff) {
    // Before the 5th at 5pm — voting for prior month (e.g. Aug 1–5 → July)
    target.setUTCMonth(target.getUTCMonth() - 1)
  }
  // After the 5th at 5pm — voting for current month

  const year  = target.getUTCFullYear()
  const month = String(target.getUTCMonth() + 1).padStart(2, "0")
  const monthKey   = `${year}-${month}`
  const monthLabel = target.toLocaleDateString("en-US", { month: "long", year: "numeric", timeZone: "UTC" })

  return { monthKey, monthLabel, isClosed }
}

// ─── Token map ────────────────────────────────────────────────────────────────
// Single source of truth for voter tokens. Also stored in Supabase `tokens` table.

export const TOKEN_MAP = {
  "Doug Bedell":      "610b5m6909576i23",
  "Miranda Delatore": "1u692h1t480h1z6h",
  "Nicole Eckl":      "0a2k59070s3a6o0r",
  "Lauren Fields":    "4w360h313p2o3w33",
  "Chrissy Hand":     "3a3t46344z4q226b",
  "Greg Hart":        "59485o351k0o594u",
  "Jen Miesse":       "3k211u6x6h3s2c00",
  "John Priskorn":    "634q1k551s4w665c",
  "Bridget Readey":   "563046285n4p0e6m",
  "Bill Sicheneder":  "3f2u660b0e0h380t",
  "Mike Waldman":     "4h6m4i39282w6l1e",
  "Megan Wetzel":     "5m640x6v6p4t6726",
}

// Admin names → their voter tokens (subset of TOKEN_MAP)
export const ADMIN_TOKENS = {
  "Bridget Readey": "563046285n4p0e6m",
  "Greg Hart":      "59485o351k0o594u",
  "Megan Wetzel":   "5m640x6v6p4t6726",
}

// Portrait URL from name — files live in public/ as firstname-lastname.jpg
export function portraitUrl(name) {
  return `${import.meta.env.BASE_URL}${name.toLowerCase().replace(/\s+/g, '-')}.jpg`
}

// Generate a cryptographically random token
export function generateToken() {
  const arr = new Uint8Array(12)
  crypto.getRandomValues(arr)
  return Array.from(arr, b => b.toString(36).padStart(2, "0")).join("").slice(0, 16)
}

// Token map: { token: voterName }
// Stored in votes.json under the key "_tokens"
// Shape of votes.json:
// {
//   "_tokens": { "abc123": "Greg Hart", ... },        // generated by admin
//   "2026-06": { "Greg Hart": "Miranda Delatore", ... } // month -> voter -> choice
// }
